name = "day_12_2"
description = "Advent of code day 12, part 2"
version = "0.1.0-dev"

authors = ["Jose Alexis"]
maintainers = ["Jose Alexis <jose.alexis.paez.thurgood@gmail.com>"]
maintainers-logins = ["alexispaez"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["day_12_2"]
